### ISSUE TITLE
All messages are acked in Subscription#subscribe

### ISSUE THREAD

**Issue by jage** [twingly/twingly-amqp#13]
When we add an exception handler all messages are "acknowledged". We need to be able to re-queue messages for queue where we can't lose messages.

**Comment by roback** [comment]
We could just add an argument to `Subscribe.new` (`requeue_on_error: false`) or should the requeue be set based on the exception?

(how to requeue: http://www.rubydoc.info/github/ruby-amqp/bunny/Bunny/Channel#reject-instance_method)

**Comment by roback** [comment]
Im thinking of creating a `Message` class which subscription.subscribe gives to the block, instead of only the payload (which it is now).

```ruby
subscription.subscribe do |message|
  message         # => Twingly::AMQP::Message
  message.payload # => { url: "http://..." }

  message.ack     # default
  message.reject
  message.discard
end
```

This way it will be easier to expose the messages `metadata` and `delivery_info` (see [the docs](http://rubybunny.info/articles/queues.html#handling_messages_with_a_block)).

**Comment by jage** [comment]
I like it.

**Comment by roback** [comment]
Hmm... How to handle multiple "messages" in one payload: https://github.com/twingly/zambezi/commit/432bde61e1bd8f0014f6c76405fa01d46149f4ef ?

**Comment by roback** [comment]
Found it: https://github.com/twingly/zambezi/blob/master/lib/binlog/queue.rb#L99-L101 :smile:
